# Generated by Django 6.0.2 on 2026-02-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('AGENT', 'Support Agent')], default='CUSTOMER', max_length=20),
        ),
    ]
