# Generated by Django 6.0.2 on 2026-02-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('AGENT', 'Support Agent'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
