# Generated by Django 6.0.2 on 2026-02-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='govt_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
