# Generated by Django 6.0.2 on 2026-03-09 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notificationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('aadhaar_linked', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('font_size', models.CharField(choices=[('normal', 'Normal'), ('large', 'Large'), ('xlarge', 'Extra Large')], default='normal', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('ta', 'Tamil')], default='en', max_length=5)),
                ('mic_enabled', models.BooleanField(default=True)),
                ('quick_chips_enabled', models.BooleanField(default=True)),
                ('chat_language', models.CharField(choices=[('en', 'English'), ('ta', 'Tamil')], default='en', max_length=5)),
                ('notif_sms', models.BooleanField(default=True)),
                ('notif_email', models.BooleanField(default=True)),
                ('notif_inapp', models.BooleanField(default=False)),
                ('notif_escalation', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
