# Generated by Django 6.0.2 on 2026-03-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='chat_language',
            field=models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('hi', 'Hindi'), ('te', 'Telugu'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('mr', 'Marathi'), ('bn', 'Bengali')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('hi', 'Hindi'), ('te', 'Telugu'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('mr', 'Marathi'), ('bn', 'Bengali')], default='en', max_length=5),
        ),
    ]
