# Generated by Django 6.0.2 on 2026-02-09 04:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversation',
            new_name='ChatRoom',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='conversation',
            new_name='room',
        ),
    ]
