# Generated by Django 6.0.2 on 2026-03-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='location_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
