# Generated by Django 6.0.2 on 2026-03-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic', '0002_complaint_latitude_complaint_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='agent_active',
            field=models.BooleanField(default=False, help_text='True when a human agent has taken over. AI will not respond.'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='agent_ended_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when agent ended takeover', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='agent_joined_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when agent took over', null=True),
        ),
    ]
