# Generated by Django 6.0.2 on 2026-03-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic', '0003_chatsession_agent_active_chatsession_agent_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('hi', 'Hindi'), ('te', 'Telugu'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('mr', 'Marathi'), ('bn', 'Bengali')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='documentsrequired',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('hi', 'Hindi'), ('te', 'Telugu'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('mr', 'Marathi'), ('bn', 'Bengali')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('hi', 'Hindi'), ('te', 'Telugu'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('mr', 'Marathi'), ('bn', 'Bengali')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('hi', 'Hindi'), ('te', 'Telugu'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('mr', 'Marathi'), ('bn', 'Bengali')], default='en', max_length=2),
        ),
    ]
